version: 2
updates:
  # Enable version updates for yarn: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      # Allow only production updates to cut down on dependabot noise
      - dependency-type: "production"
    schedule:
      interval: "weekly"

